export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  PATIENTS: "/dashboard/patients",
  CREATE_PATIENT: "/dashboard/patients/new",
  PATIENT_PROFILE: (patientId: string) => `/dashboard/patients/${patientId}`,
  PATIENT_FAMILY: (patientId: string) => `/dashboard/patients/${patientId}/family`,
  PATIENT_MEMORIES: (patientId: string) => `/dashboard/patients/${patientId}/memories`,
  PATIENT_LIVE: (patientId: string) => `/dashboard/patients/${patientId}/live`,
  PATIENT_REPETITION: (patientId: string) => `/dashboard/patients/${patientId}/repetition`,
  PATIENT_DISTRESS: (patientId: string) => `/dashboard/patients/${patientId}/distress`,
  PATIENT_PATTERNS: (patientId: string) => `/dashboard/patients/${patientId}/patterns`,
  PATIENT_CONNECTION: (patientId: string) => `/dashboard/patients/${patientId}/connection`,
  PATIENT_CONSENT: (patientId: string) => `/dashboard/patients/${patientId}/consent`,
  ALERTS: "/dashboard/alerts",
  ALERT_DETAIL: (alertId: string) => `/dashboard/alerts/${alertId}`,
  SETTINGS: "/dashboard/settings",
  PROFILE: "/dashboard/profile",
};
